language: python
python:
- '2.7'
addons:
  postgresql: 9.3
cache:
  apt: true
  directories:
  - $HOME/.pip-cache/
before_install:
- gem install sass
- npm install karma
- npm install
script:
- python manage.py test
- "cd dkobo/koboform/static/js/sut && $HOME/node_modules/karma/bin/karma start --browsers PhantomJS --config=karma.conf.js --single-run"
env:
- PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache DJANGO_DEBUG=False DJANGO_SECRET_KEY=ZGtvYm90cmF2aXM
install:
- pip install -r requirements.txt --use-mirrors
- python manage.py syncdb --noinput --settings=dkobo.settings
- python manage.py migrate --noinput --settings=dkobo.settings
deploy:
  provider: heroku
  app: kobo-dev
  api_key:
    secure: pXD088HFHTBgl9z6E+u3LwcfQO4D1Cpa3IrocAky5bitlKC0ku55JoTKOQLYmNsI0eCCQw+uJKD8F7OuLwt4zZ7LF30SbtPbs1g73vFz7Iu6sV4uY97MKC01T6CCiaOfUACeY8UP/tQfFgaugRE6D2I3GyQ/k6tKiR2hQX2pqOI=
  strategy: git
notifications:
  irc: irc.freenode.org#kobotest
